# yaml-language-server: $schema=https://docs.mergify.com/mergify-configuration-schema.json

queue_rules:
  - name: default
    queue_conditions:
      - base=main
      - label~=merge-queue|dependencies
    merge_conditions:
      - check-success = nix-flake-check
      - check-success = Garnix CI / All Garnix checks
    merge_method: rebase

pull_request_rules:
  - name: merge using the merge queue
    conditions: []
    actions:
      queue:
